//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.AppData.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int idRoom { get; set; }
        public int idUser { get; set; }
        public string role { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual Users Users { get; set; }
        public Link()
        {
            
        }
        public Link(int idRoom, int idUser, string role) 
        {
            this.idRoom = idRoom;
            this.idUser = idUser;
            this.role = role;
        }
    }
}
